### ISSUE TITLE
Download damaged

### ISSUE THREAD

**Issue by marsbarf** [jameshball/osci-render#167]
I am able to install Osci-render but when I run it, I'm told the app is damaged? Does Osci-render work on Apple M2?

**Comment by DJLevel3** [comment]
I would assume something has caused Apple's Rosetta framework to fail to translate osci-render, so there will probably have to be a new build specifically targeting ARM.

**Comment by jameshball** [comment]
Hi, thanks for making an issue. This happens because I don't pay (a lot of money!) for the apple developer license which is required to sign applications. This means you need to bypass this message.

https://support.apple.com/en-gb/HT202491 this or 
https://iboysoft.com/news/app-is-damaged-and-cannot-be-opened.html this (under "How to fix 'File/App is damaged and cannot be opened' on macOS Ventura/Big Sur?") should explain how to do that.

It should work fine on M1/M2 but let me know if this doesn't work

**Comment by marsbarf** [comment]
Got it. Thank you James! Thank you for a fantastic piece of software!
