### ISSUE TITLE
Save and load configuration from file

### ISSUE THREAD

**Issue by metriics** [jameshball/osci-render#36]
When reopening osci-render, all options are reset to default. It would be useful to have the ability to save and load configuration files for any cool effects the user creates.

## Reasons for
* Save and share cool effects
* Prevents going through each option to pick up where you left off
* Could also add the ability to save a certain config file as default
* Can be accomplished with built-in libraries

## Reasons against
* Requires adding some GUI elements to save and load configs, maybe a reset button to go back to the defaults for the loaded config
  * Unrelated; right-click to reset a property to default?
* How 'deep' to go? Do we save just the property values, or do we include the selected file/folder and MIDI configuration? What if they are no longer available?

## Potential implementation
Add a config manager class that handles the saving, loading and parsing of config files.
This could potentially be done using Java's built-in XML and IO libraries, theoretically making file IO and XML parsing an easy implementation.

**Comment by jameshball** [comment]
Thanks for opening an issue! This is next on my list of features to implement - been on my mind for a while now. Thanks for the detail too.

Just to store my thoughts somewhere, these are some additional features I was thinking of implementing with regards to this:

- Ability to save .obj, .txt, and .svg files with the project file itself for portability
- Save MIDI channel bindings so that you don't need to manually bind channels every time

**Comment by jameshball** [comment]
This is now merged, and should appear on releases as 1.15.0 - if there are any bugs, please make another issue!
