### ISSUE TITLE
Fine details in .svg totally incorrect

### ISSUE THREAD

**Issue by DJLevel3** [jameshball/osci-render#40]
I'm trying to render some .svg files I have, but the images produced are totally incorrect. In some cases, you can tell what is supposed to be drawn, but the fine details are all over the place and make the audio noisy and the image distorted. The image also goes out of frame and clips at the edges. I have no idea how this is happening or how it could be fixed, but this isn't a problem on simple shapes.

[Example](https://youtu.be/KzKDmRc8AT0)
[Expected first frame](https://drive.google.com/file/d/1JOVQ22khy6fNibm9VQh6DG-i6qu-i9gz/view?usp=sharing)

**Comment by jameshball** [comment]
I will have a proper look at this tomorrow, but poorly drawn SVGs is usually a problem with the SVG file itself. If the lines aren't drawn in a 'logical' order (e.g. they draw one line and then move over to another line far away) then it will draw terribly on the oscilloscope because there is so much distance to keep jumping.

I see the original SVG has a lot of lines that are dashed slightly - if those are not drawn after each other in the SVG that could explain it.

I'm going to take a look at the SVG tomorrow to see whether that's right or not :) Probably also worth you seeing if you can save the SVG differently, or try and isolate the problem to just a few lines of SVG path, for example.

**Comment by jameshball** [comment]
Actually, a good way to test this would be to use the trace effect and see the order it draws lines

**Comment by jameshball** [comment]
![image](https://user-images.githubusercontent.com/38670946/146614373-041fb52b-449d-4c50-9ca1-950e21796e2f.png)

Also, looks like a massive amount of complexity when zooming in - just experimenting with simplifying the SVG now

**Comment by jameshball** [comment]
There's also this to have a look at if you used Inkscape: https://graphicdesign.stackexchange.com/questions/122499/automatically-reduce-remove-some-nodes-to-smooth-an-svg

**Comment by DJLevel3** [comment]
I exported the SVG directly from Blender using the Freestyle SVG Exporter. The model is needlessly complex and I tried to reduce that as much as I could.

**Comment by jameshball** [comment]
Found some fairly major rendering bugs that cause this! This is now what the SVG looks like:

![image](https://user-images.githubusercontent.com/38670946/146643583-60e2cefa-50e8-4537-a9cd-722df1667d59.png)
